services:
  seaweedfs:
    image: chrislusf/seaweedfs@sha256:43b768cd62b00d132439cda881b93fd1adebf1b315e996e794087743821d771d
    command:
      - server
      - -dir=/data
      - -master.port=9333
      - -volume.port=8080
      - -filer
      - -filer.port=8888
      - -s3
      - -s3.port=8333
      - -s3.config=/etc/seaweedfs/s3.json
    ports:
      - "8333:8333"
    volumes:
      - seaweedfs-data:/data
      - ./s3.json:/etc/seaweedfs/s3.json:ro

volumes:
  seaweedfs-data:
